### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by mhihasan** [davidchambers/doctest#132]
Doctest works well without `export` statement. But if I want to add export command, it is throwing exception. 

Suppose, a filename is `file.js`
```js
const foo = () => {
     return "bar"
}

export {foo}
```
While I am trying to add doctest to this file, I am getting `Unexpected token` error for the `export` command. like
```js
const foo = () => {
     return "bar"
}

export {foo}

// > foo()
// bar
```

How to fix this? Thanks in advance.

**Comment by davidchambers** [comment]
The most recent npm release does not support `import` and `export`, but the `master` branch on GitHub does.

Try running these commands:

```console
$ npm install 'doctest@davidchambers/doctest#2505091a87d18ce9754f0e5e3cd07caeee7da3d5'

$ node_modules/.bin/doctest --module esm -- file.js
```

Let me know whether this works for you. :)

**Comment by mhihasan** [comment]
When are you planning to release master?
A follow up question: 
How to run all the files in current directory excluding some directory like node_modules or any dir?

**Comment by davidchambers** [comment]
> When are you planning to release master?

This question suggests a release in the near future would be appreciated. :)

> How to run all the files in current directory excluding some directory like `node_modules` or any dir?

This depends on your platform. I suggest using `find` if you have access to it (run `man find` to determine this).

Recursively list all JavaScript files, starting in the current directory:

```console
$ find . -name '*.js'
```

Exclude __node_modules__:

```console
$ find . -name '*.js' -not -path './node_modules/*'
```

The most robust way to provide this list of file paths to `doctest` is to use `xargs`:

```console
$ find . -name '*.js' -not -path './node_modules/*' | xargs -n 1 node_modules/.bin/doctest --module esm --
```

To handle file paths that contain spaces, provide `-print0` to `find` and `-0` to `xargs`:

```console
$ find . -name '*.js' -not -path './node_modules/*' -print0 | xargs -0 -n 1 node_modules/.bin/doctest --module esm --
```

You may also find the `-depth` and `-maxdepth` primaries (predicates) useful.
