### ISSUE TITLE
Support variables in doctests

### ISSUE THREAD

**Issue by eush77** [davidchambers/doctest#40]
I would like `doctest` to process variable declarations and assignments so that I could check a function for side effects.
```js
/**
 * > var array = [0, 1, 2]
 * > array.shift()
 * 0
 * > array
 * [1, 2]
 */
```

Currently it is possible in non-strict mode (with `var` omitted) and in strict mode in CommonJS eval mode (due to #39).

What do you think? Does this feature fit in?

**Comment by davidchambers** [comment]
Closing as I don't think there's a real solution.
