### ISSUE TITLE
remove browser support

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/doctest#62]
This project could be simplified significantly were it to target Node exclusively. Is anyone out there running doctest in the browser?

**Comment by danse** [comment]
Hey, a lot of activity on this recently, that's good news! Personally i never run this in the browser, but i often used it in order to test code written for the browser

**Comment by davidchambers** [comment]
> Hey, a lot of activity on this recently, that's good news!

I had a busy weekend. :)

> Personally i never run this in the browser, but i often used it in order to test code written for the browser

Could you elaborate? Do the modules you're testing reference `window` anywhere, or are they CommonJS modules which can be tested in Node?

**Comment by danse** [comment]
I was mostly referring to module systems which can be used in Browsers. We added support for AMD in the past and i used it, with a project based on Require, nowadays i am working almost all the time with Angular, which kind of prevents me from using Doctest. Hopefully in the future modularisation in Javascript will follow just one standard, but currently there is still some fragmentation, so i think that keeping room for alternative module systems still has quite some value. Of course this needs to be balanced with the cost in terms of complexity

**Comment by davidchambers** [comment]
Thanks for providing more detail, Francesco. :)

I'm going to put together a pull request just to *see* how much infrastructure we could remove from the project if we removed the ability to run doctests in the browser.

**Comment by danse** [comment]
Sure! :sun_with_face: As far as i remember, our approach for supporting custom running environments in the past was based on mocking necessary objects like `module.exports` or `require`. This might work also for `window`, `angular` or others. If this is implemented as a preliminary step, it does not affect the logic used eventually to extract, run and check the tests. This approach has several limitations and is not very elegant, but it might help somebody to actually use Doctest in their projects, without a big cost in terms of complexity in Doctest's code

**Comment by davidchambers** [comment]
> As far as i remember, our approach for supporting custom running environments in the past was based on mocking necessary objects like `module.exports` or `require`. This might work also for `window`, `angular` or others.

That's a good idea. I'd like to wait for a concrete use case before doing so. I currently only use doctest to test Node modules, so my needs are already met. :)

> I'm going to put together a pull request just to *see* how much infrastructure we could remove from the project if we removed the ability to run doctests in the browser.

https://github.com/davidchambers/doctest/compare/master...no-browser

**Comment by danse** [comment]
> master...no-browser

I see that you are keeping support for different module systems there, so all fine :)

**Comment by dnalot** [comment]
Have you seen [Doctest.js](http://ianb.github.io/doctestjs/)? It's specialized for browser (if you deprecate it) and never quite got [Node support](https://github.com/ianb/doctestjs/issues/15).

**Comment by davidchambers** [comment]
I'm aware of that project. It seems overly complex to me. I want a way to ensure the examples in my documentation stay up to date; I've no desire to replace unit tests with doctests. Doctests are great for pure, synchronous functions. Asynchronous functions are better tested by unit tests.

**Comment by dnalot** [comment]
:+1: I meant if you drop browser support you could point users there.

**Comment by davidchambers** [comment]
Yep. Thanks for the suggestion! :)

**Comment by danse** [comment]
@dnalot `Doctest.js` does not provide actual doctests, and it has no commits in the last two years. If testing in the browser has even a minimal utility, this project can easily keep supporting it
