### ISSUE TITLE
Writing return value in multiple lines

### ISSUE THREAD

**Issue by zhangchiqing** [davidchambers/doctest#66]
This works fine
```
// > add(1, 2);
// { sum: 3 }
function add(a, b) {
  return {
    sum: a + b
  };
}
```

But this will throw error
```
// > add(1, 2);
// {
//   sum: 3
// }
function add(a, b) {
  return {
    sum: a + b
  };
}
```

```
$ doctest sdfsdf.js
retrieving sdfsdf.js...
running doctests in sdfsdf.js...

  error: line 32: Unexpected token ;

```

Right now, if I write the return value in multiple lines, doctest will throw the above error.

In my case, sometimes the return value could be as complex as an array of nested objects, which I prefer to write in multiple lines instead of one line. 

Does it support multiple lines?
Thanks!

**Comment by davidchambers** [comment]
This is supported (but not documented). Begin each of the wrapped lines with a `.`. For example:

```javascript
// > add(1, 2)
// {
// . sum: 3
// . }
function add(a, b) {
  return {
    sum: a + b
  };
}
```

This works for wrapped input lines as well.

Let me know if this works for you. :)

**Comment by zhangchiqing** [comment]
Nice! It works :+1:

Thanks a lot!
