### ISSUE TITLE
ES6 class method support

### ISSUE THREAD

**Issue by sprengerjo** [davidchambers/doctest#80]
Is it possible to use doctest within class syntax. I get an "Unexpected token ." exception if i try that.

Here is what i did:

```javascript
class MyTest {
// toFahrenheit :: Number -> Number
//
// Convert degrees Celsius to degrees Fahrenheit.
//
// > toFahrenheit(0)
// 32
// > toFahrenheit(100)
// 212
  toFahrenheit(degreesCelsius) {
    return degreesCelsius * 9 / 5 + 32;
  }
}
module.exports = MyTest;
```

**Comment by davidchambers** [comment]
Doctests get replaced by function calls, so doctests must only appear in contexts in which a function call could appear. This is valid:

```javascript
// Celsius.toFahrenheit :: Number -> Number
//
// Convert degrees Celsius to degrees Fahrenheit.
//
// ```javascript
// > Celsius.toFahrenheit(0)
// 32
//
// > Celsius.toFahrenheit(100)
// 212
// ```
class Celsius {
  static toFahrenheit(degreesCelsius) {
    return degreesCelsius * 9 / 5 + 32;
  }
}
```

If you're interested in understanding why your example results in a syntax error, see the output of `doctest --print -- path/to/file.js`.

**Comment by sprengerjo** [comment]
Thank you. It is working with non-static calls too: 
`
// Celsius.toFahrenheit :: Number -> Number
//
// Convert degrees Celsius to degrees Fahrenheit.
//
// ```javascript
// > new Celsius().toFahrenheit(0)
// 32
//
// > new Celsius().toFahrenheit(100)
// 212
// ```
class Celsius {
  toFahrenheit(degreesCelsius) {
    return degreesCelsius * 9 / 5 + 32;
  }
}
`

**Comment by davidchambers** [comment]
By the way, @sprengerjo, one can use triple backticks to format code blocks on GitHub:

    ```javascript
    console.log('Hello, world!');
    ```

```javascript
console.log('Hello, world!');
```
