### ISSUE TITLE
JSDoc style via dox

### ISSUE THREAD

**Issue by jmatsushita** [davidchambers/doctest#81]
Hi there,

Have you considered leaving the parsing to https://github.com/tj/dox which is a fairly light-weight way to gain jsdoc-style comments (which has a big ecosystem) and focus on test generation with doctest?

Cheers,

Jun
PS: If that removes the fun of doing parsers in a functional style, then maybe doing an interpreter for various test frameworks would bring some excitement :) ?

**Comment by davidchambers** [comment]
I don't want to clutter my projects with JSDoc cruft, @jmatsushita. ;)

The Sanctuary source code, for example, is beautiful. I'd like to keep it this way. :)

You're welcome to fork this project and go in a different direction.

**Comment by danse** [comment]
Haha i see that i'm not the only one with opinions about JSDoc annotations! :)
